# Generated by Django 5.1.6 on 2025-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='student.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
